includes:
- configs/s2ef/2M/base.yml

model:
  name: schnet
  hidden_channels: 1024
  num_filters: 256
  num_interactions: 5
  num_gaussians: 200
  cutoff: 6.0
  use_pbc: True
  regress_relaxed_energy: True
  regress_relaxed_position: True

optim:
  batch_size: 24
  eval_batch_size: 16
  num_workers: 64
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones: # epochs at which lr_initial <- lr_initial * lr_gamma
    - 5
    - 8
    - 10
  warmup_epochs: 3
  warmup_factor: 0.2
  max_epochs: 30
  energy_coefficient: 1
  force_coefficient: 100
  relaxed_pos_coefficient: 1
  relaxed_energy_coefficient: 1
  use_position_diff: True
