includes:
- /checkpoint/abhshkdz/ocp_oct1_configs/s2ef/20M/base.yml

model:
  name: schnet
  hidden_channels: 1024
  num_filters: 256
  num_interactions: 5
  num_gaussians: 200
  cutoff: 6.0
  use_pbc: True
  otf_graph: True

optim:
  batch_size: 32
  eval_batch_size: 8
  eval_every: -10000
  num_workers: 64
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones: # epochs at which lr_initial <- lr_initial * lr_gamma
    - 5
    - 8
    - 10
  warmup_epochs: 3
  warmup_factor: 0.2
  max_epochs: 30
  force_coefficient: 100
