includes:
- configs/2020_07_13_ocp_reset_200k/base_dist.yml

model:
  name: dimenet
  hidden_channels: 128
  num_blocks: 1
  cutoff: 6.0
  num_after_skip: 1
  num_output_layers: 1
  use_pbc: False

optim:
  batch_size: 4
  eval_batch_size: 2
  num_workers: 64
  lr_initial: 0.0001
  lr_gamma: 0.1
  num_gps: 8
  lr_milestones: # epochs at which lr_initial <- lr_initial * lr_gamma
    - 5
    - 8
  warmup_epochs: 3
  warmup_factor: 0.2
  max_epochs: 30
  force_coefficient: 100
