include-paths: 
  - src/fairchem/applications/cattsunami
  - packages/fairchem-applications-cattsunami/
tag-prefix: fairchem_applications_cattsunami
tag-template: 'fairchem_applications_cattsunami-$RESOLVED_VERSION'
name-template: 'fairchem_applications_cattsunami-$RESOLVED_VERSION'
exclude-contributors: [github-actions] 
categories:
  - title: New Features
    labels: [enhancement]
  - title: Bug Fixes
    labels: [bug]
  - title: ðŸ›  Enhancements
    labels: [enhancement]
  - title: Documentation
    labels: [documentation]
  - title: Tests
    labels: [test]
  - title: Deprecations
    labels: [deprecation]
  - title: Dependencies
    labels: [dependencies]
  - title: Other Changes
    labels: ["*"]
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'dependencies'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Whatâ€™s Changed

  $CHANGES