includes:
- configs/is2re/10k/base.yml

model:
  name: dimenetplusplus
  hidden_channels: 256
  out_emb_channels: 192
  num_blocks: 3
  cutoff: 6.0
  num_radial: 6
  num_spherical: 7
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3
  regress_forces: False
  use_pbc: True

optim:
  batch_size: 2
  eval_batch_size: 2
  num_workers: 8
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones: # epochs at which lr_initial <- lr_initial * lr_gamma
    - 4
    - 8
    - 12
  warmup_epochs: 2
  warmup_factor: 0.2
  max_epochs: 20
