[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-fancy-pypi-readme>=24"]
build-backend = "hatchling.build"

[project]
name = "fairchem-applications-adsorbml"
dynamic = ["version", "readme"]
description = "Module for calculating the minima adsorbtion energy"
license = {text = "MIT License"}

[project.urls]
repository = "https://github.com/FAIR-Chem/fairchem/tree/main/src/fairchem/applications/AdsorbML"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../../"
git_describe_command = 'git describe --tags --match  fairchem_applications_adsorbml-*'

[tool.hatch.build.targets.sdist]
sources = ["src"]
only-include = ["src/fairchem/applications/AdsorbML"]

[tool.hatch.build.targets.wheel]
sources = ["src"]
only-include = ["src/fairchem/applications/AdsorbML"]

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"
fragments = [
  { path = "src/fairchem/applications/AdsorbML/README.md" },
  { path = "src/fairchem/applications/AdsorbML/LICENSE.md" },
]
