[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-fancy-pypi-readme>=24"]
build-backend = "hatchling.build"

[project]
name = "fairchem-data-oc"
dynamic = ["version", "readme"]
description = "Code for generating adsorbate-catalyst input configurations"
license = {text = "MIT License"}

[project.urls]
repository = "https://github.com/FAIR-Chem/fairchem/tree/main/src/fairchem/data/oc"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../../"
git_describe_command = 'git describe --tags --match  fairchem_data_oc-*'

[tool.hatch.build]
directory = "../../dist"

[tool.hatch.build.targets.sdist]
only-include = ["src/fairchem/data/oc"]

[tool.hatch.build.targets.wheel]
sources = ["src"]
only-include = ["src/fairchem/data/oc"]

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"
fragments = [
  { path = "src/fairchem/data/oc/README.md" }
]

[tool.ruff.lint.per-file-ignores]
# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
"src/fairchem/data/oc/core/__init__.py" = ["F401"]
"src/fairchem/data/oc/utils/__init__.py" = ["F401"]
