job:
  mem: 32GB
  cpus: 4
  gres: gpu:rtx8000:1
  partition: long
  time: 20:00:00

default:
  test_ri: True
  mode: train
  graph_rewiring: remove-tag-0
  model:
    phys_embeds: True
    tag_hidden_channels: 64
    pg_hidden_channels: 0  # shall have been 32
    energy_head: 'weighted-av-initial-embeds' # False ?
  wandb_tags: 'edge-embed-test'
  optim:
    max_epochs: 15
    batch_size: 256
    eval_batch_size: 256
  cp_data_to_tmpdir: true

runs:
  - config: faenet-is2re-all  # 2678275
    note: 'all rij'
    frame_averaging: 2D
    fa_frames: se3-random
    model:
      edge_embed_type: all_rij
      mp_type: base
  - config: faenet-is2re-all  # 2678276
    note: 'all'
    frame_averaging: 2D
    fa_frames: se3-random
    model:
      edge_embed_type: all
      mp_type: base
  - config: sfarinet-is2re-all  # 2678277
    note: 'all rij sfarinet'
    frame_averaging: 2D
    fa_frames: se3-random
    model:
      edge_embed_type: all_rij
      mp_type: sfarinet
  - config: sfarinet-is2re-all  # 2678278
    note: 'sfarinet all'
    frame_averaging: 2D
    fa_frames: se3-random
    model:
      edge_embed_type: all
      mp_type: sfarinet
  - config: sfarinet-is2re-all  # 2678279
    note: 'sfarinet all'
    frame_averaging: 2D
    fa_frames: se3-random
    model:
      edge_embed_type: all
      mp_type: base
      skip_co: "concat"
      complex_mp: true
      graph_norm: true
      second_layer_mlp: true