job:
  mem: 32GB
  cpus: 4
  gres: gpu:rtx8000:1
  partition: long
  time: 20:00:00

default:
  test_ri: True
  mode: train
  graph_rewiring: remove-tag-0
  model:
    phys_embeds: True
    tag_hidden_channels: 64
    pg_hidden_channels: 0  # shall have been 32
    energy_head: 'weighted-av-initial-embeds' # False ?
    edge_embed_type: all_rij
  wandb_tags: 'mp-type'
  optim:
    max_epochs: 5
    batch_size: 256
    eval_batch_size: 256

runs:
  - config: faenet-is2re-all
    note: 'faenet no sym'
  - config: faenet-is2re-all
    note: 'faenet baseline sym'
    frame_averaging: 2D
    fa_frames: se3-random
  - config: faenet-is2re-all
    note: 'faenet baseline sym'
    frame_averaging: 2D
    fa_frames: se3-random
  - config: faenet-is2re-all
    note: 'simple'
    frame_averaging: 2D
    fa_frames: se3-random
    model:
      mp_type: simple
  - config: faenet-is2re-all
    note: 'base'
    frame_averaging: 2D
    fa_frames: se3-random
    model:
      mp_type: base
  - config: faenet-is2re-all
    note: 'updownscale'
    frame_averaging: 2D
    fa_frames: se3-random
    model:
      mp_type: updownscale
  - config: faenet-is2re-all
    note: 'base'
    frame_averaging: 2D
    fa_frames: se3-random
    model:
      mp_type: base
    optim:
      lr_initial: 0.0005
  - config: faenet-is2re-all
    note: 'all'
    frame_averaging: 2D
    fa_frames: se3-random
    model:
      mp_type: 
    optim:
      lr_initial: 0.0001
    mp_type: base
  - config: faenet-is2re-all
    note: 'smaller lr'
    frame_averaging: 2D
    fa_frames: se3-random
    model:
      mp_type: updownscale
    optim:
      lr_initial: 0.0005
  - config: faenet-is2re-all
    note: 'small warmup factor and lr'
    frame_averaging: 2D
    fa_frames: se3-random
    model:
      mp_type: base
    optim:
      lr_initial: 0.0005
      warmup_factor: 0.01
  - config: faenet-is2re-all
    note: 'warmup factor + lr'
    frame_averaging: 2D
    fa_frames: se3-random
    model: 
      mp_type: base
    optim:
      lr_initial: 0.0005
      warmup_factor: 0.5
  - config: faenet-is2re-all
    note: 'big batch size'
    frame_averaging: 2D
    fa_frames: se3-random
    model: 
      mp_type: base
    optim:
      batch_size: 328
      eval_batch_size: 328
  - config: faenet-is2re-all
    note: 'smaller batch'
    frame_averaging: 2D
    fa_frames: se3-random
    model: 
      mp_type: base
    optim:
      batch_size: 180
      eval_batch_size: 180
  - config: faenet-is2re-all
    note: 'smaller hidden smaller lr'
    frame_averaging: 2D
    fa_frames: se3-random
    model:
      mp_type: base
      hidden_channels: 180
    optim: 
      lr_initial: 0.0005