job:
  mem: 48GB
  cpus: 4
  gres: gpu:rtx8000:1
  partition: long
  time: 20:00:00

default:
  test_ri: True
  mode: train
  graph_rewiring: remove-tag-0
  model:
    phys_embeds: True
    tag_hidden_channels: 64
    pg_hidden_channels: 0  # shall have been 32
    energy_head: False # False ?
  optim:
    max_epochs: 5
    batch_size: 196
    eval_batch_size: 196
  wandb_tags: 's2ef-sym-prop'

runs:
  - config: sfarinet-s2ef-2M
    note: 'Baseline 5 epochs 1 Gpu'
    frame_averaging: 2D
    fa_frames: all
    model:
      regress_forces: from_energy
  - config: sfarinet-s2ef-2M
    note: 'Baseline 5 epochs 1 Gpu'
    frame_averaging: 3D
    fa_frames: all
    model:
      regress_forces: from_energy
  - config: sfarinet-s2ef-2M  # 2659788
    note: '2D all gradient'
    frame_averaging: 2D
    fa_frames: all
    model:
      regress_forces: direct_with_gradient_target
  - config: sfarinet-s2ef-2M  # 2659789
    note: '2d all no gradient'
    frame_averaging: 2D
    fa_frames: all
    model:
      regress_forces: direct
